name: Deploy GitHub Pages

on:
  workflow_run:
    workflows: ["CI/CD - Funcionários"]
    types: [completed]                    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Montar site com relatórios
        run: |
          rm -rf site
          mkdir -p site/relatorios site/cobertura
          # copia os HTML/JSON do repositório (produzidos no job de testes)
          cp -r funcionarios/test-report/* site/relatorios/ || true
          cp -r funcionarios/coverage/* site/cobertura/     || true
          # um index simples apontando para os relatórios
          cat > site/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <title>Relatórios do Projeto</title>
          <h1>Relatórios</h1>
          <ul>
            <li><a href="relatorios/jest-report.html">Relatório de Testes (HTML)</a></li>
            <li><a href="relatorios/jest-report.json">Relatório de Testes (JSON)</a></li>
            <li><a href="cobertura/index.html">Cobertura de Código (HTML)</a></li>
          </ul>
          HTML

      - name: Upload artifact para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
